
name: Send Reminder Emails

on:
  schedule:
    - cron: "0 15 * * 1-6"   # 15:00 UTC = 10:00 Lima
  workflow_dispatch:

jobs:
  send-daily:
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
      DATABASE_URL : ${{ secrets.DATABASE_URL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_PROMPT_ID: ${{ secrets.OPENAI_PROMPT_ID }}
      OPENAI_PROMPT_VERSION: ${{ secrets.OPENAI_PROMPT_VERSION }}
      SUMMARY_PROMPT_ID: ${{ secrets.SUMMARY_PROMPT_ID }}
      SUMMARY_PROMPT_VERSION: ${{ secrets.SUMMARY_PROMPT_VERSION }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
      GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION || '3.11' }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run send_reminder
        run: python -m app.jobs.send_reminder
